// Jetpack Compose Stability Configuration
// Referans: https://developer.android.com/develop/ui/compose/performance/stability/fix#configuration-file

// Standart kütüphane sınıfları
java.time.Instant
java.time.LocalDate
java.time.LocalDateTime
java.time.ZonedDateTime
java.util.UUID

// Proje içi (Domain ve Data katmanı)
com.example.rencar_pair.domain.model.*
com.example.rencar_pair.data.remote.dto.*
